### ISSUE TITLE
Colors aren't consistent

### ISSUE THREAD

**Issue by SkelyTony** [flathub/com.vscodium.codium#47]
![image](https://user-images.githubusercontent.com/78977752/125505499-8a1efa3f-7d03-4344-ad69-787a477da66f.png)

**Comment by Smittyvb** [comment]
What colours aren't consistent? That looks right to me.

**Comment by SkelyTony** [comment]
![image](https://user-images.githubusercontent.com/78977752/125669410-fd41682a-fc9d-44d1-805a-931668a5fceb.png)
this bar

**Comment by noonsleeper** [comment]
Hi @SkelyTony but can you give us more details, this work as espected on vscode or code-os flatpak? works on regular codium or vscode? What WM or DE are you using?

**Comment by SkelyTony** [comment]
Form what I've seen, vscodium form other sources has the bar black. I am on Arch and kde so kwin is my wm. It isn't a big problem for me but I just wanted to know if there's a fix
![image](https://user-images.githubusercontent.com/78977752/125825392-50014dfa-6a70-4277-810c-76066b99646e.png)

**Comment by Smittyvb** [comment]
@SkelyTony I am also running kwin and it is the right color for me. I think the color for the top bar is based on the system wide theme, so changing the system theme to dark mode should fix the issue for you.

**Comment by SkelyTony** [comment]
I use dark them on kde and the bar is white 
![image](https://user-images.githubusercontent.com/78977752/126481614-12ce015a-58e9-4349-b472-b08bbcf3988f.png)

**Comment by noonsleeper** [comment]
@SkelyTony  Is your theme in the flatpak repo? Try to search and install on gnome flatpak try to download this automatically for example adwaita-dark 
```
% flatpak search adwaita-dark
Name                             Description                                     Application ID                           Version          Branch          Remotes
Adwaita dark GTK theme           Dark variant of the Adwaita GTK theme           org.gtk.Gtk3theme.Adwaita-dark                            3.22            flathub
```

**Comment by tobikrs** [comment]
I run in to the same problem when I installed `vscodium` with flatpak on elementaryos with having a light grey menu bar even though I'm using a dark theme...
Installing the theme with flatpak didn't fix it.

But as suggested [here](https://stackoverflow.com/a/51832782) just changing `window.titleBarStyle` from `native` to `custom` in the VSCodium Settings fixed it for me.

![image](https://user-images.githubusercontent.com/39905423/127978688-cc658ece-25b2-48e0-8808-68f059408cd0.png)

**Comment by noonsleeper** [comment]
@tobikrs Thnaks for your solution!

**Comment by noonsleeper** [comment]
@SkelyTony I'll close this ticket that has many moths without updates. If you have another question / bug don't hesitate and open a new ticket.
